name: 'SourceCrafter.ViewModelGenerator: build, test & deploy'

on:
  push:
    branches: [ "**" ]

jobs:
  build:
    name: .NET 7 Build, test
    runs-on: 'ubuntu-latest'

    steps:      
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Test
      run: dotnet test SourceCrafter.ViewModelGenerator.UnitTests/SourceCrafter.ViewModelGenerator.UnitTests.csproj --verbosity normal -c Release

    - name: Pack
      if: github.ref_name == 'dev'
      run: |
        without_comma=$(echo "${{ github.event.head_commit.message }}" | sed 's/,/\\u002C/g')
        dotnet pack SourceCrafter.ViewModelGenerator/SourceCrafter.ViewModelGenerator.csproj --verbosity normal -c Release /p:PackageReleaseNotes="$without_comma"
    
    - name: Publish to Nuget
      if: github.ref_name == 'dev'
      run: |
        package="$(find . -wholename '**/Release/*.nupkg' -exec echo "{}" \;)"
        dotnet nuget push $package --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
